apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  ports:
  - name: 5001-5001
    port: 30080
    protocol: TCP
    targetPort: 5000
  selector:
    app: frontend
  type: NodePort
