apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
        app: frontend
    spec:
      containers:
      - image: olmy2016/frontend
        name: frontend
        ports:
        - containerPort: 5000
        resources: {}
        env:
        - name: BACKEND_URL
          value: http://backend-service:5001

