apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
        app: backend
    spec:
      containers:
      - image: olmy2016/backend
        name: backend
        ports:
        - containerPort: 5001

